import "../env-config";

import openapiTS, { astToString } from "openapi-typescript";

async function fetchSchema(url: string) {
  const response = await fetch(url);
  const schema = await response.json();

  for (const path in schema.paths) {
    for (const method in schema.paths[path]) {
      if (method === "parameters") {
        continue;
      }

      const operation = schema.paths[path][method];
      if (!operation) {
        continue;
      }

      operation.responses = operation.responses || {};

      operation.responses["default"] = {
        description: "Error",
        content: {
          "application/json": {
            schema: { $ref: "#/components/schemas/ErrorModel" },
          },
        },
      };
    }
  }

  return schema;
}

function addComments(contents: string) {
  return (
    // biome-ignore lint/style/useTemplate: Generated by openapi
    `
  /**
  * This file was auto-generated by openapi-typescript.
  * Do not make direct changes to the file.
  */
    ` + contents
  );
}

async function generateTypes(url: string) {
  const transformedSchema = await fetchSchema(url);

  const ast = await openapiTS(transformedSchema);
  const contents = addComments(astToString(ast));

  await Bun.write("./src/lib/api/openapi.ts", contents);
}

if (process.argv.includes("--help")) {
  console.log(`
    Usage: bun run gen-types -- --env [environment]

    Options:
      --env       Specify the environment to use (default: local)
      --help      Show help
  `);

  process.exit(0);
}

const envIndex = process.argv.indexOf("--env");

const env =
  envIndex !== -1 && process.argv[envIndex + 1]
    ? process.argv[envIndex + 1]
    : "local";

console.log(`Running in ${env} environment`);

const BACKEND_HOST =
  process.env["NEXT_PUBLIC_BACKEND_HOST"] || "localhost:8000";

const BACKEND_API_BASE_URL =
  process.env["NEXT_PUBLIC_NO_HTTPS"] === "true"
    ? `http://${BACKEND_HOST}/`
    : `https://${BACKEND_HOST}/`;

console.log(`Using url:`, BACKEND_API_BASE_URL);

const openApiUrl = `${BACKEND_API_BASE_URL}api/docs/json`;

generateTypes(openApiUrl).catch(console.error);
