/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
export interface paths {
  "/api/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Users */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              users: {
                id: string;
                email: string | null;
                phone: string | null;
                /** Format: date-time */
                createdAt: string | null;
                /** Format: date-time */
                updatedAt: string | null;
              }[];
            };
          };
        };
        /** @description Error */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorModel"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/self": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              email: string | null;
              phone: string | null;
              /** Format: date-time */
              createdAt: string | null;
              /** Format: date-time */
              updatedAt: string | null;
            };
          };
        };
        /** @description Error */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorModel"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorModel: {
      /**
       * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
       * @example Bad Request
       */
      title: string;
      /**
       * @description HTTP status code
       * @example 400
       */
      status:
        | 100
        | 102
        | 103
        | 200
        | 201
        | 202
        | 203
        | 206
        | 207
        | 208
        | 226
        | 300
        | 301
        | 302
        | 303
        | 305
        | 306
        | 307
        | 308
        | 400
        | 401
        | 402
        | 403
        | 404
        | 405
        | 406
        | 407
        | 408
        | 409
        | 410
        | 411
        | 412
        | 413
        | 414
        | 415
        | 416
        | 417
        | 418
        | 421
        | 422
        | 423
        | 424
        | 425
        | 426
        | 428
        | 429
        | 431
        | 451
        | 500
        | 501
        | 502
        | 503
        | 504
        | 505
        | 506
        | 507
        | 508
        | 510
        | 511;
      /**
       * @description A human-readable explanation specific to this occurrence of the problem.
       * @example Property foo is required but is missing.
       */
      detail: string;
      /** @description Optional list of individual error details. */
      errors?: {
        /** @description Error message text */
        message: string;
        /** @description Where the error occurred, e.g. 'body.items[3].tags */
        location: string;
        /** @description The value at the given location */
        value: string;
      }[];
    };
    User: {
      id: string;
      email: string | null;
      phone: string | null;
      /** Format: date-time */
      createdAt: string | null;
      /** Format: date-time */
      updatedAt: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
